[create_incident]
is_custom      = 1
label          = Create Incident
description    = Creates an incident in Alert Manager React
payload_format = json
icon_path      = appIcon.png

param.severity    = medium
param.title       =
param.description =
