[incidents_lookup]
external_type = kvstore
collection    = incidents
fields_list   = _key,incident_id,title,description,severity,status,assigned_to,assigned_role,created_by,source_alert,created_time,updated_time,resolved_time

[incident_comments_lookup]
external_type = kvstore
collection    = incident_comments
fields_list   = _key,incident_id,author,comment,timestamp,status_change
