[bm_tree_config]
external_type = kvstore
collection = bm_tree_config
fields_list = _key, tree_spl

[bm_services]
external_type = kvstore
collection = bm_services
fields_list = _key, service_name, service_description, service_spl

[bm_mappings]
external_type = kvstore
collection = bm_mappings
fields_list = _key, node_id, service_name

[bm_results]
external_type = kvstore
collection = bm_results
fields_list = _key, node_id, service_name, service_status, last_checked_time, run_id, error_message

[bm_run_log]
external_type = kvstore
collection = bm_run_log
fields_list = _key, run_id, run_start_time, run_duration_sec, run_success_count, run_error_count
