[bm_tree_config]
external_type = kvstore
collection = bm_tree_config
fields_list = _key, tree_query

[bm_services]
external_type = kvstore
collection = bm_services
fields_list = _key, name, description, spl_query

[bm_mappings]
external_type = kvstore
collection = bm_mappings
fields_list = _key, host_id, service_name

[bm_results]
external_type = kvstore
collection = bm_results
fields_list = _key, host_id, service_name, status, last_checked
