// Mock tree data matching the ITRS State Tree structure.
// status: 'ok' | 'warning' | 'critical' | 'unknown'
// type: 'group' (expandable) | 'query' (leaf — has results)

const q = (id, label, status, description, sampleInfo, columns, rows) => ({
  id, label, status, type: 'query', description,
  sampleInfo: sampleInfo || '1 row, Sampling every 60 seconds, Last sample 08:43:02',
  columns, rows,
});

export const TREE = {
  id: 'root',
  label: 'Global State',
  status: 'critical',
  type: 'group',
  children: [
    {
      id: 'americas',
      label: 'Americas',
      status: 'critical',
      type: 'group',
      children: [
        {
          id: 'geneos',
          label: 'Geneos',
          status: 'ok',
          type: 'group',
          children: [
            {
              id: 'itrs',
              label: 'ITRS',
              status: 'ok',
              type: 'group',
              children: [
                q('gw2stats', 'GW2 Stats', 'ok',
                  'GW2 gateway statistics',
                  '2 rows, Sampling every 60 seconds, Last sample 08:43:02',
                  ['GATEWAY', 'STATUS', 'UPTIME'],
                  [{ GATEWAY: 'GW2', STATUS: 'Connected', UPTIME: '99.9%' }]),
              ],
            },
          ],
        },
        {
          id: 'infrastructure',
          label: 'Infrastructure',
          status: 'ok',
          type: 'group',
          children: [],
        },
        {
          id: 'clearing',
          label: 'Clearing',
          status: 'critical',
          type: 'group',
          children: [
            {
              id: 'clearing-proc',
              label: 'Clearing-Processing',
              status: 'critical',
              type: 'group',
              children: [
                {
                  id: 'usvweqaacpati01',
                  label: 'USVWEQAACPATI01',
                  status: 'critical',
                  type: 'group',
                  children: [
                    {
                      id: 'cpu-grp',
                      label: 'CPU',
                      status: 'ok',
                      type: 'group',
                      children: [
                        q('cpu', 'CPU', 'ok', 'CPU utilization', null,
                          ['METRIC', 'VALUE', 'THRESHOLD'],
                          [{ METRIC: 'CPU Usage', VALUE: '45%', THRESHOLD: '80%' }]),
                      ],
                    },
                    {
                      id: 'disk-grp',
                      label: 'DISK',
                      status: 'ok',
                      type: 'group',
                      children: [
                        q('diskspace', 'DiskSpace', 'ok', 'Disk space utilization',
                          '2 rows, Sampling every 60 seconds, Last sample 08:43:02',
                          ['DRIVE', 'USED', 'FREE', 'TOTAL'],
                          [
                            { DRIVE: 'C:', USED: '120 GB', FREE: '80 GB', TOTAL: '200 GB' },
                            { DRIVE: 'D:', USED: '500 GB', FREE: '500 GB', TOTAL: '1 TB' },
                          ]),
                      ],
                    },
                    {
                      id: 'fkm-grp',
                      label: 'FKM',
                      status: 'ok',
                      type: 'group',
                      children: [
                        q('nt-event-logs', 'NT Event Logs', 'ok',
                          'Windows NT Event Log monitoring', '0 rows, Sampling every 60 seconds',
                          ['LEVEL', 'SOURCE', 'EVENT_ID', 'MESSAGE'], []),
                      ],
                    },
                    {
                      id: 'hw-grp',
                      label: 'HARDWARE',
                      status: 'ok',
                      type: 'group',
                      children: [
                        q('nt-hardware', 'NT-HARDWARE', 'ok', 'Hardware monitoring', null,
                          ['COMPONENT', 'STATUS', 'VALUE'],
                          [{ COMPONENT: 'Memory', STATUS: 'OK', VALUE: '16 GB' }]),
                      ],
                    },
                    {
                      id: 'net-grp',
                      label: 'NETWORK',
                      status: 'ok',
                      type: 'group',
                      children: [
                        q('nt-network', 'NT-NETWORK', 'ok', 'Network interface monitoring', null,
                          ['INTERFACE', 'STATUS', 'SPEED'],
                          [{ INTERFACE: 'eth0', STATUS: 'UP', SPEED: '1 Gbps' }]),
                      ],
                    },
                    {
                      id: 'perfmon-grp',
                      label: 'PERFMON',
                      status: 'ok',
                      type: 'group',
                      children: [
                        q('memory-usage', 'Memory-Usage', 'ok',
                          'Memory performance counters', null,
                          ['METRIC', 'VALUE', 'THRESHOLD'],
                          [{ METRIC: 'Available MB', VALUE: '4096', THRESHOLD: '1024' }]),
                      ],
                    },
                    {
                      id: 'sql-toolkit',
                      label: 'SQL-TOOLKIT',
                      status: 'critical',
                      type: 'group',
                      children: [
                        q('ca-prices', 'CA Prices', 'ok', 'CA Prices feed monitoring', null,
                          ['SOURCE', 'STATUS', 'COUNT'],
                          [{ SOURCE: 'CA', STATUS: 'OK', COUNT: '150' }]),
                        q('duration', 'Duration', 'ok', 'Batch job duration monitoring', null,
                          ['JOB', 'SCHEDULED_DURATION', 'ACTUAL_DURATION'], []),
                        q('end', 'End', 'ok', 'Batch job end-time monitoring', null,
                          ['JOB', 'EXPECTED_END', 'ACTUAL_END'], []),
                        q('error', 'Error', 'critical', 'Batch job error monitoring',
                          '1 row, Sampling every 60 seconds, Last sample 08:43:02',
                          ['JOB', 'ERROR_CODE', 'MESSAGE', 'TIME'],
                          [{ JOB: 'BATCH_EQ_RECON', ERROR_CODE: '1001', MESSAGE: 'Connection timeout', TIME: '02:34:11' }]),
                        q('mics-top5', 'MICS Top 5 sessions', 'ok',
                          'Top 5 ONLINE sessions in MICS and number of trades waiting to be processed',
                          '1 row, Sampling every 60 seconds, Last sample 08:43:02',
                          ['SOURCE', 'TRIGGER', 'SESSION', 'COUNT'],
                          [{ SOURCE: 'GXI TRC ACG', TRIGGER: 'READY', SESSION: '999', COUNT: '25' }]),
                        q('ods-trade', 'ODS Trade Count', 'ok', 'ODS trade count monitoring', null,
                          ['SYSTEM', 'COUNT', 'STATUS'],
                          [{ SYSTEM: 'ODS', COUNT: '1524', STATUS: 'OK' }]),
                        q('seq-num', 'SequenceNumber', 'ok', 'Sequence number gap detection', null,
                          ['SEQ_FROM', 'SEQ_TO', 'GAP_COUNT'], []),
                        q('sla-delay', 'SLA_Delay', 'ok', 'SLA delay monitoring', null,
                          ['JOB', 'SLA_MINUTES', 'DELAY_MINUTES'], []),
                        q('start', 'Start', 'ok', 'Batch job start-time monitoring', null,
                          ['JOB', 'SCHEDULED_START', 'ACTUAL_START'], []),
                        q('stored-proc', 'StoredProcedure', 'ok', 'Stored procedure execution monitoring', null,
                          ['PROC_NAME', 'STATUS', 'DURATION_MS'], []),
                        q('tables-1', 'Tables', 'ok', 'Table row count monitoring', null,
                          ['TABLE_NAME', 'ROW_COUNT', 'STATUS'], []),
                        q('tables-2', 'Tables', 'ok', 'Table size monitoring', null,
                          ['TABLE_NAME', 'SIZE_MB', 'STATUS'], []),
                        q('tables-3', 'Tables', 'ok', 'Table lock monitoring', null,
                          ['TABLE_NAME', 'LOCK_COUNT', 'STATUS'], []),
                        q('ready-status', 'Trades in READY status', 'ok',
                          'Trades sitting in READY status — should be processed quickly', null,
                          ['SYSTEM', 'COUNT', 'OLDEST_AGE'],
                          [{ SYSTEM: 'MICS', COUNT: '12', OLDEST_AGE: '00:05:23' }]),
                        q('not-rtrm', 'Trades not sent to RTRM', 'ok',
                          'Trades pending transmission to RTRM', null,
                          ['TRADE_ID', 'AGE', 'REASON'], []),
                      ],
                    },
                    {
                      id: 'toolkit-grp',
                      label: 'TOOLKIT',
                      status: 'ok',
                      type: 'group',
                      children: [
                        q('check-time', 'check-time-server-batch', 'ok',
                          'Server time synchronisation check', null,
                          ['SERVER', 'LOCAL_TIME', 'NTP_OFFSET'],
                          [{ SERVER: 'USVWEQAACPATI01', LOCAL_TIME: '08:43:02', NTP_OFFSET: '+0.002s' }]),
                      ],
                    },
                    {
                      id: 'winsvc-grp',
                      label: 'WIN-SERVICES',
                      status: 'ok',
                      type: 'group',
                      children: [
                        q('winservices', 'WinServices', 'ok', 'Windows services status', null,
                          ['SERVICE', 'STATUS', 'START_TYPE'],
                          [
                            { SERVICE: 'MSSQLSERVER', STATUS: 'Running', START_TYPE: 'Auto' },
                            { SERVICE: 'SQLAgent', STATUS: 'Running', START_TYPE: 'Auto' },
                          ]),
                      ],
                    },
                  ],
                },
                {
                  id: 'tradecap-main',
                  label: 'TradeCap - MAIN',
                  status: 'warning',
                  type: 'group',
                  children: [
                    {
                      id: 'prod',
                      label: 'PROD',
                      status: 'warning',
                      type: 'group',
                      children: [
                        q('app27', 'USVWSCAACPAPP27', 'ok', 'App server monitoring', null,
                          ['METRIC', 'VALUE'], []),
                        q('map01', 'USVWSCAACPMAP01', 'warning', 'MAP server monitoring', null,
                          ['METRIC', 'VALUE', 'STATUS'],
                          [{ METRIC: 'Heap Usage', VALUE: '88%', STATUS: 'WARN' }]),
                        q('oa01', 'USVWSCAACPOA01', 'ok', 'OA server monitoring', null,
                          ['METRIC', 'VALUE'], []),
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'gw-info',
      label: 'GW_trs_002 Info',
      status: 'ok',
      type: 'group',
      children: [],
    },
  ],
};
