[create_incident]
label = Create Incident
description = Creates an incident record in Alert Manager when this alert fires
payload_format = json
is_custom = 1

param.severity = medium
param.title =
param.description =
